{% set base_name = "libignition-rendering" %}
{% set version = "4.7.0" %}
{% set name = base_name  + version.split('.')[0] %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/ignitionrobotics/ign-rendering/archive/ignition-rendering{{ version.split('.')[0] }}_{{ version }}.tar.gz
  sha256: f9c23e604e785b7a2352686f044964899b87146dc2000a9f1ddfa04fd09560c9
  patches:
    - ogre-version.patch

build:
  number: 1
  run_exports:
    - {{ pin_subpackage(name, max_pin='x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - cmake
    - make                               # [not win]
    - pkg-config                         # [not win]

    # x11
    - {{ cdt('mesa-libgl-devel') }}      # [unix]
    - {{ cdt('mesa-dri-drivers') }}      # [unix]
    - {{ cdt('libselinux') }}            # [linux]
    - {{ cdt('libxdamage') }}            # [linux]
    - {{ cdt('libxxf86vm') }}            # [linux]
    - {{ cdt('libxfixes') }}             # [linux]
    - {{ cdt('libxext') }}               # [linux]
    - {{ cdt('libxau') }}                # [linux]
  host:
    - xorg-libx11                        # [unix]
    - xorg-libxext                       # [unix]
    - libglu                             # [linux]
    - libignition-math6 >=6.6
    - libignition-common3
    - libignition-plugin1
    - ogre  {{ ogre }}
  run:
    - xorg-libx11                        # [unix]
    - xorg-libxext                       # [unix]
    - libglu                             # [linux]
    - libignition-math6 >=6.6
    - libignition-common3
    - libignition-plugin1
    - {{ pin_compatible('ogre', max_pin='x.x') }}
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx and x86_64]

test:
  commands:
    - test -f ${PREFIX}/include/ignition/rendering{{ version.split('.')[0] }}/ignition/rendering.hh  # [not win]
    - test -f ${PREFIX}/lib/libignition-rendering{{ version.split('.')[0] }}.so  # [linux]
    - test -f ${PREFIX}/lib/libignition-rendering{{ version.split('.')[0] }}.dylib  # [osx]
    - test -f ${PREFIX}/lib/cmake/ignition-rendering{{ version.split('.')[0] }}/ignition-rendering{{ version.split('.')[0] }}-config.cmake  # [not win]
    - if exist %PREFIX%\\Library\\include\\ignition\\rendering{{ version.split('.')[0] }}\\ignition\\rendering.hh (exit 0) else (exit 1)  # [win]
    - if exist $PREFIX$\\Library\\lib\\ignition-rendering{{ version.split('.')[0] }}.lib (exit 0) else (exit 1)  # [win]
    - if exist $PREFIX$\\Library\\bin\\ignition-rendering{{ version.split('.')[0] }}.dll (exit 0) else (exit 1)  # [win]
    - if exist %PREFIX%\\Library\\lib\\cmake\\ignition-rendering{{ version.split('.')[0] }}\\ignition-rendering{{ version.split('.')[0] }}-config.cmake (exit 0) else (exit 1)  # [win]

about:
  home: https://github.com/ignitionrobotics/ign-rendering
  license: Apache-2.0
  license_file: LICENSE
  summary: Ignition Rendering

extra:
  recipe-maintainers:
    - JShep1
    - wolfv
    - traversaro
