{% set base_name = "libignition-rendering" %}
{% set version = "5_5.1.0" %}
{% set version_package = version.split('_')[1] %}
{% set major_version = version.split('_')[0] %}
{% set name = base_name  + major_version %}

package:
  name: {{ name }}
  version: {{ version_package }}

source:
  url: https://github.com/ignitionrobotics/ign-rendering/archive/ignition-rendering{{ version }}.tar.gz
  sha256: a26fe32f2dd849bb2ae492fc65b73e730f830f5bf9d763c9e62b6d6672ccf02f
  patches:
    - ogre-version.patch

build:
  number: 1
  run_exports:
    - {{ pin_subpackage(name, max_pin='x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - cmake
    - make                               # [not win]
    - pkg-config                         # [not win]

    # x11
    - {{ cdt('mesa-libgl-devel') }}      # [unix]
    - {{ cdt('mesa-dri-drivers') }}      # [unix]
    - {{ cdt('libselinux') }}            # [linux]
    - {{ cdt('libxdamage') }}            # [linux]
    - {{ cdt('libxxf86vm') }}            # [linux]
    - {{ cdt('libxfixes') }}             # [linux]
    - {{ cdt('libxext') }}               # [linux]
    - {{ cdt('libxau') }}                # [linux]
  host:
    - xorg-libx11                        # [unix]
    - xorg-libxext                       # [unix]
    - libglu                             # [linux]
    - libignition-math6 >=6.6
    - libignition-common4
    - libignition-plugin1
    - libignition-utils1
    - ogre  {{ ogre }}
  run:
    - xorg-libx11                        # [unix]
    - xorg-libxext                       # [unix]
    - libglu                             # [linux]
    - {{ pin_compatible('ogre', max_pin='x.x') }}
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx and x86_64]

test:
  commands:
    - test -f ${PREFIX}/include/ignition/rendering{{ major_version  }}/ignition/rendering.hh  # [not win]
    - test -f ${PREFIX}/lib/libignition-rendering{{ major_version }}.so  # [linux]
    - test -f ${PREFIX}/lib/libignition-rendering{{ major_version }}.dylib  # [osx]
    - test -f ${PREFIX}/lib/cmake/ignition-rendering{{ major_version }}/ignition-rendering{{ major_version }}-config.cmake  # [not win]
    - if exist %PREFIX%\\Library\\include\\ignition\\rendering{{ major_version }}\\ignition\\rendering.hh (exit 0) else (exit 1)  # [win]
    - if exist $PREFIX$\\Library\\lib\\ignition-rendering{{ major_version }}.lib (exit 0) else (exit 1)  # [win]
    - if exist $PREFIX$\\Library\\bin\\ignition-rendering{{ major_version }}.dll (exit 0) else (exit 1)  # [win]
    - if exist %PREFIX%\\Library\\lib\\cmake\\ignition-rendering{{ major_version }}\\ignition-rendering{{ version.split('.')[0] }}-config.cmake (exit 0) else (exit 1)  # [win]

about:
  home: https://github.com/ignitionrobotics/ign-rendering
  license: Apache-2.0
  license_file: LICENSE
  summary: Ignition Rendering

extra:
  recipe-maintainers:
    - JShep1
    - wolfv
    - traversaro
